language: java
jdk: openjdk8
cache:
  directories:
    - closure-library
    - closure-compiler
    - closure-linter
    - python-gflags
notifications:
  email: false
before_install:
  - nvm install 11.10.1
install:
  - npm ci
  - bash ./scripts/build-dependencies.sh
script:
  - bash ./scripts/execute.sh
  - npm test
after_script:
  - mkdir public
  - cp -r ./dist/ ./public
  - cp package.json ./public
  - cd ./public
  - git init
  - git add .
  - git commit -m "update package"
  - git push --force --quiet "https://${GIT_TOKEN}@github.com/kiwikiot/libphonenumber-js-utils.git" master:master
before_deploy: echo "$(tput bold)$(tput setaf 6)Starting NPM release for version - `cat package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])"`"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
after_deploy: echo "$(tput bold)$(tput setaf 6)Completed Deployment of NPM version - `cat package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])"`"
branches:
  only:
    - dev
